#include<iostream>
#include<conio.h>
#include<stdlib.h>

using namespace std;


/*
int main(){
    int i;
    i = 10;

    do{
        cout <<i <<endl;
        i--;
    }while(i>=1);
    system("pause");
    return 0;
}

int main(){
    int i;

    i = 10;

    while(i>=1){
        cout <<i <<endl;
        i--;
    }
    getch();
    return 0;
}*/

int main(){
    
    return 0;
}